use_default_settings: true

general:
  instance_name: "all-included-searxng"

search:
  autocomplete: "google"
  formats:
    - html
    - json

server:
  secret_key: "change_me"

engines:
  - name: wolframalpha
    disabled: false
